### ISSUE TITLE
Exception: JSON Error in /Users/steffenlohbrandt/local_git/calibrate_json_mapper/package.json:LinesAndColumns$1 is not a constructor

### ISSUE THREAD

**Issue by lohbrand** [daidodo/tsimportsorter#22] opened 2020-08-13 17:51 UTC
**Code snippet triggering the exception**
```ts
// INSERT CODE HERE
```

**Logs**
(Please select ALL logs in "JS/TS Import/Export Sorter" Output window and copy/paste here)
```
INSERT LOG HERE
```

**Comment by daidodo** [comment] 2020-08-14 08:47
Duplicate of https://github.com/daidodo/tsimportsorter/issues/21.

**Closed by daidodo** 2020-08-14 08:47 UTC
Labels: duplicate
