### ISSUE TITLE
Exception: JSON Error in /Users/steffenlohbrandt/local_git/grunt-objectmapper/package.json:LinesAndColumns$1 is not a constructor

### ISSUE THREAD

**Issue by lohbrand** [daidodo/tsimportsorter#21] opened 2020-08-13 08:29 UTC
**Code snippet triggering the exception**
```ts
// INSERT CODE HERE
```

**Logs**
(Please select ALL logs in "JS/TS Import/Export Sorter" Output window and copy/paste here)
```
INSERT LOG HERE
```

**Comment by daidodo** [comment] 2020-08-14 08:46
@lohbrand, could you provide more details about the error, e.g. code snippet triggering the exception, logs, or your *package.json* content?
Thanks!

**Comment by daidodo** [comment] 2020-09-04 12:16
@lohbrand, I'll close this issue since I can neither reproduce it nor get useful information to fix it.
Feel free to reopen it if you have more questions.
Thanks!

**Closed by daidodo** 2020-09-04 12:16 UTC
Labels: bug, question
